import { char, datetime } from 'drizzle-orm/mysql-core';

/** UUIDv7 generated by the application, stored as its 36-character text form. */
export const uuidColumn = (name: string) => char(name, { length: 36 });

/** Millisecond-precision DATETIME that always holds UTC (Drizzle maps it to/from JS Date as UTC). */
export const utcDatetime = (name: string) => datetime(name, { mode: 'date', fsp: 3 });
