import { fileURLToPath, pathToFileURL } from 'node:url';
import { drizzle } from 'drizzle-orm/mysql2';
import { migrate } from 'drizzle-orm/mysql2/migrator';
import { createDatabasePool } from './client';

export const MIGRATIONS_FOLDER = fileURLToPath(new URL('./migrations', import.meta.url));

/**
 * Applies pending SQL migrations (generated by drizzle-kit and reviewed) in order.
 * MySQL DDL commits implicitly, so migrations are small, forward-only steps.
 */
export async function runMigrations(databaseUrl: string): Promise<void> {
  const pool = createDatabasePool({ url: databaseUrl, connectionLimit: 1 });
  try {
    await migrate(drizzle(pool), { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await pool.end();
  }
}

// `npm run db:migrate` — an explicit step, never run on app boot (N workers would race).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error('DATABASE_URL is not set. Copy .env.example to .env first.');
    process.exit(1);
  }
  runMigrations(databaseUrl)
    .then(() => console.warn('Migrations applied.'))
    .catch((err: unknown) => {
      console.error('Migration failed:', err);
      process.exit(1);
    });
}
